### ISSUE TITLE
謝謝你的心得

### ISSUE THREAD

**Issue by azole** [shu10111/git-workshop#1]
謝謝你的心得，也謝謝你喜歡我們的上課方式，之後關於上課的內容或節奏，總之各種問題，都歡迎隨時提出讓我知道，讓我們可以一起更好的學習，好嗎？

在學習一門新領域時，挫折絕對是必然發生的，但也表示，你正在調整你的大腦、你正在學習一個你原本不會的東西，所以，應該要很開心才對！下次遇到挫折時，試試看這樣想「對，我是遇到挫折了，但這也表示我正在把一個我原本不會的東西變成我會的，好興奮好期待我可以學會他的時候！」很抖 M，哈哈，但事實就是如此啊～

**Comment by shu10111** [comment]
謝謝老師提供遇到挫折的另一種思考模式，我會去試試看的!
